keys:
  - &admin_yodal 0FD8FF0FE607505D20B9A637500A31B1AE23676E
  - &server_oarre 5e8cce0ec807e494b2d2bcf9016c4ccc477a5a09
creation_rules:
  - path_regex: \.(yaml|json|env|ini)
    key_groups:
    - pgp:
      - *admin_yodal
      - *server_oarre
