services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:100
    group_add:
      - "303" # render group ID for access to /dev/dri/render*
    environment:
      - TZ=America/New_York
      - JELLYFIN_LOG_DIR=/var/log/jellyfin
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /var/lib/jellyfin:/config
      - /var/log/jellyfin:/var/log/jellyfin
      - /var/cache/jellyfin:/cache
      - /data/tvshows:/data/tvshows
      - /data/movies:/data/movies
    ports:
      - 8096:8096 # HTTP web UI
      - 8920:8920 # HTTPS web UI
      - 7359:7359/udp # Jellyfin client discovery
      - 1900:1900/udp # DLNA service discovery
    networks:
      - swag_default
    restart: unless-stopped
networks:
  swag_default:
    external: true
