services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=2200
      - PGID=2001
      - UMASK=002
      - TZ=America/New_York
      - URL=thevoidbetween.us
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - EMAIL=ga29smith@gmail.com
    volumes:
      - /var/lib/swag:/config
    ports:
      - 443:443
      - 80:80
    networks:
      - reverse_proxy
    restart: unless-stopped
networks:
  reverse_proxy:
    name: reverse_proxy
