services:
  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient
    environment:
      - PUID=2100
      - PGID=2001
      - TZ=America/New_York
    volumes:
      - /var/lib/ddclient:/config
    restart: unless-stopped
